export const DEFAULT_GREEN_CIRCLE_RADIUS = 70;
export const DEFAULT_WHITE_CIRCLE_RADIUS = 20;
export const DEFAULT_GRAY_CIRCLE_RADIUS = 2000;
export const MINIMUM_ZOOM_LEVEL = 15;
export const SLIDER_MINIMUM_VALUE = 100;
export const SLIDER_MAXIMUM_VALUE = 5000;